apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: matrixcanvas
  description: Interactive matrix visualization tool
  annotations:
    github.com/project-slug: ithun-y-ittesaf/MatrixCanvas
  tags:
    - typescript
    - react
    - vite
    - education
spec:
  type: website
  lifecycle: experimental
  owner: user:default/guest
